#ACCUEILCONTROLLER
acceuil:
    path: /acceuil
    controller: 'App\Controller\Acceuil\AcceuilController::index'
homepage:
    path: /
    controller: 'App\Controller\Acceuil\AcceuilController::acceuil'
acceuilclient:
    path: /acceuilclient
    controller: 'App\Controller\Acceuil\AcceuilController::acceuilclient'
acceuiladmin:
    path: /acceuiladmin
    controller: 'App\Controller\Acceuil\AcceuilController::acceuiladmin'
#Client
client:
    path: /client
    controller: App\Controller\Client\ClientController::index
client_new:
    path: /client/new
    controller: App\Controller\ClientController::new
    methods: [GET, POST]
#ContactController
contact:
    path: /contact
    controller: 'App\Controller\Contact\ContactController::index'

contactclient:
    path: /contactclient
    controller: 'App\Controller\Contact\ContactController::contact/client'
#RechercheTraverséeController
recherchetraverseeclient:
    path: /recherchetraverseeclient
    controller: App\Controller\RechercheTraversee\RechercheTraverseeController::recherchetraverseeclient
recherchetraversee:
    path: /recherchetraversee
    controller: App\Controller\RechercheTraversee\RechercheTraverseeController::index
#ResultRechercheController
resultrecherche:
    path: /resultrecherche
    controller: App\Controller\ResultRechercheController::index
    methods: ['GET']
resultrechercheclient:
    path: /resultrechercheclient
    controller: App\Controller\ResultRechercheController::resultrechercheclient
    methods: ['GET']
#Connection
connection:
    path: /connection
    controller: App\Controller\Connection\ConnectionController::index
#Réservation
reservation:
    path: /reservation
    controller: App\Controller\Reservation\ReservationController::index
reservation_new:
    path: /reservation/new
    controller: App\Controller\ReservationController::new
    methods: [GET, POST]
reservation_client_new:
    path: /reservation/client/new
    controller: App\Controller\ReservationClientController::new
    methods: [GET, POST]
confirmation:
    path: /confirmation
    controller: App\Controller\Confirmation\ConfirmationController::index
admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::index
traversee:
    path: /traversee
    controller: App\Controller\Traversee\TraverseeController::index
bateau:
    path: /bateau
    controller: App\Controller\Bateau\BateauController::index
equipement:
    path: /equipement
    controller: App\Controller\Equipement\EquipementController::index
port:
    path: /port
    controller: App\Controller\Port\PortController::index
liaison:
    path: /liaison
    controller: App\Controller\Liaison\LiaisonController::index